version: '3.8'
services:
  postgres:
    image: postgres:16  # ou postgres:15
    container_name: postgres_intelifones
    environment:
      POSTGRES_DB: fones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fones
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: